[tool.poetry]
name = "ruff-pre-commit"
version = "0.0.1"
description = ""
authors = ["Charlie Marsh <charlie.r.marsh@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
ruff = "^0.0.65"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
